name       : libisoburn
version    : 1.3.8
release    : 1
source     :
    - http://files.libburnia-project.org/releases/libisoburn-1.3.8.tar.gz : b75c9a7f17faab5280ddc34ea6610c4e8bcf630762ee386d10bc52c4b50f6806
license    : GPL-2.0
summary    : libisoburn is a frontend for libraries libburn and libisofs
description: |
    libisoburn is a frontend for libraries libburn and libisofs which enables creation and expansion of ISO-9660 filesystems on all CD/DVD/BD media supported by libburn. This includes media like DVD+RW, which do not support multi-session management on media level and even plain disk files or block devices.
    
    The price for that is thorough specialization on data files in ISO-9660 filesystem images. So libisoburn is not suitable for audio (CD-DA) or any other CD layout which does not entirely consist of ISO-9660 sessions.
    
    For more general writing of CD/DVD/BD see libburn and its command line application cdrskin.
builddeps  :
    - pkgconfig(libburn-1)
    - pkgconfig(libisofs-1)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
