name       : libisoburn
version    : 1.4.6
release    : 2
source     :
    - http://files.libburnia-project.org/releases/libisoburn-1.4.6.tar.gz : 69efe9490e9ed6dbb1d8cad387ccaf5dcc5bb39dd466eef208a6b77a48584def
license    : GPL-2.0
component  : programming.library
summary    : libisoburn is a frontend for libraries libburn and libisofs
description: |
    libisoburn is a frontend for libraries libburn and libisofs which enables creation and expansion of ISO-9660 filesystems on all CD/DVD/BD media supported by libburn. This includes media like DVD+RW, which do not support multi-session management on media level and even plain disk files or block devices.
builddeps  :
    - pkgconfig(libburn-1)
    - pkgconfig(libisofs-1)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
