name       : libisoburn
version    : 1.5.6
release    : 6
source     :
    - https://files.libburnia-project.org/releases/libisoburn-1.5.6.tar.gz : 2b80a6f73dd633a5d243facbe97a15e5c9a07644a5e1a242c219b9375a45f71b
homepage   : https://dev.lovelyhq.com/libburnia/libisoburn
license    : GPL-2.0-or-later
component  : programming.library
summary    : libisoburn is a frontend for libraries libburn and libisofs
description: |
    libisoburn is a frontend for libraries libburn and libisofs which enables creation and expansion of ISO-9660 filesystems on all CD/DVD/BD media supported by libburn. This includes media like DVD+RW, which do not support multi-session management on media level and even plain disk files or block devices.
builddeps  :
    - pkgconfig(libburn-1)
    - pkgconfig(libisofs-1)
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
